server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cdcdemo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: root
    password: 152189
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: ""
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false

mybatis-plus:
  mapper-locations: "classpath*:/mapper/**/*.xml"
  type-aliases-package: com.example.cdcdemo.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-prefix: ""
